### ISSUE TITLE
Should this repository point to bitbucket.org/energistics/etp-devkit?

### ISSUE THREAD

**Issue by stianlagstad** [pds-technology/etp-devkit#1]
Hi,

Should this repository point to https://bitbucket.org/energistics/etp-devkit now? It looks like there's more recent activity there.

I have the same question for https://github.com/pds-technology/etp.net vs https://bitbucket.org/energistics/etp.net.

Thanks!

**Comment by EricGriffith** [comment]
The Energistics repository on BitBucket is the master repository.  However, we maintain our own internal copy, which is not always in sync with that.  When we push new versions of WITSMLstudio Store and WITSMLstudio Desktop here to GitHub, we also publish the versions of etp-devkit / etp.net repositories here that are used by Store and Desktop.

If you are creating your own project, you should use the Energistics repository.  If you are using our Desktop / Store repositories, then you should use the repositories here with Store / Desktop.

**Comment by stianlagstad** [comment]
Thank you very much! Can I suggest adding a small notice in the readme's of those two projects saying that?

**Comment by EricGriffith** [comment]
We'll look into it, but it's not clear how to do it since they are always "eventually consistent".  We don't maintain the repositories here as "permanent" forks that go in different directions.

**Comment by stianlagstad** [comment]
Thanks again for the quick response! Please feel free to close this (or wait until you've made a decision on that).
